<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
	    <meta http-equiv="X-UA-Compatible" content="IE=edge">
	    <meta name="viewport" content="width=device-width, initial-scale=1">
	    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		<title><?=$GLOBALS['title']?> :: Limber Logic Learning</title>
	</head>
	<body>
		<div class="fluid-container">
			<h1>Users</h1>
			<table class="table table-border table-striped table-hover">
				<thead>
					<tr>
						<th>Email</th>
						<th>Name</th>
						<th>Age</th>
					</tr>
				</thead>
				<tbody>
					<?php foreach($GLOBALS['users']->data as $email => $user) : ?>
						<tr>
<!-- 							<td><?php var_dump($GLOBALS['users']) ?></td> -->
							<td><?=$user['email']?></td>
							<td><?=$user['name']?></td>
							<td><?=$user['age']?></td>
						</tr>
					<?php endforeach ?>
				</tbody>
			</table>
		</div>
		
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	</body>
</html>